#  This should run on any environment:
#       Docker version: 18.06.1
#       Docker-compose 1.17.1
version: '3.7'
services:
  web:
    build: .
    image: chardmd/tweets-web
    container_name: web
    command: npm run dev
    restart: unless-stopped
    networks:
      - tweets-network
    environment:
      NODE_ENV: production
      BASE_URL: '${BASE_URL}'
      PORT: 8080
      HOME_PAGE_URL: '${HOME_PAGE_URL}'
      MONGODB_URI: '${MONGODB_URI}'
      SESSION_SECRET: '${SESSION_SECRET}'
      SENTRY_DSN: '${SENTRY_DSN}'
      MAX_PROJECT_COUNT: '${MAX_PROJECT_COUNT}'
      TWITTER_API_KEY: '${TWITTER_API_KEY}'
      TWITTER_API_SECRET: '${TWITTER_API_SECRET}'
      TWITTER_ACCESS_TOKEN: '${TWITTER_ACCESS_TOKEN}'
      TWITTER_TOKEN_SECRET: '${TWITTER_TOKEN_SECRET}'
      STRIPE_PKEY: '${STRIPE_PKEY}'
      STRIPE_SKEY: '${STRIPE_SKEY}'
      STRIPE_PAYMENT_METHODS: '${STRIPE_PAYMENT_METHODS}'
      STRIPE_SUBSCRIPTION_ID: '${STRIPE_SUBSCRIPTION_ID}'
      STRIPE_PRICE: '${STRIPE_PRICE}'
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules

  proxy:
    build:
      context: ./nginx-conf
      dockerfile: Dockerfile-default
    image: chardmd/tweets-proxy
    container_name: proxy
    restart: unless-stopped
    networks:
      - tweets-network
    ports:
      - 80:80
    depends_on:
      - web

networks:
  tweets-network:
    driver: overlay
