#  This should run on any environment:
#       Docker version: 18.06.1
#       Docker-compose 1.17.1
version: "3.7"
services:
  web:
    build: .
    image: chardmd/tweets-web
    container_name: web
    command: npm run dev
    restart: unless-stopped
    networks:
      - tweets-network
    environment:
      NODE_ENV: production
      PORT: 8080
      BASE_URL: "${BASE_URL}"
      HOME_PAGE_URL: "${HOME_PAGE_URL}"
      MONGODB_URI: "${MONGODB_URI}"
      SESSION_SECRET: "${SESSION_SECRET}"
      TWITTER_KEY: "${TWITTER_KEY}"
      TWITTER_SECRET: "${TWITTER_SECRET}"
      SENTRY_DSN: "${SENTRY_DSN}"
    volumes:
    - .:/home/node/app
    - /home/node/app/node_modules

  proxy:
    build: 
      context: ./nginx-conf
      dockerfile: Dockerfile-default
    image: chardmd/tweets-proxy
    container_name: proxy
    restart: unless-stopped
    networks:
      - tweets-network
    ports:
      - 80:80
    depends_on:
      - web

networks:
  tweets-network:
    driver: overlay
