FROM nginx:mainline-alpine

RUN rm /etc/nginx/conf.d/default.conf

# dhparam-2048.pem was generated via:
#
#   sudo openssl dhparam -out dhparam-2048.pem 2048
#
COPY ./dhparam-2048.pem /etc/ssl/certs/

#
# This defines the site configuration for the production nginx.
#
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
